### ISSUE TITLE
Open Brodcast Server

### ISSUE THREAD

**Issue by ulamnet** [volio/AnotherLive#13]
Hello , users how to get open broadcast server key?

thanks.

**Comment by solarhell** [comment]
This app relies on so many cloud service providers which are in China, so it is difficult for you to make this app work only if you know Chinese and go to register those accounts(such as LeTV).

**Comment by ulamnet** [comment]
do you have "key etc..." ? for me ?

**Comment by solarhell** [comment]
You will get these keys after you register these cloud service provider.

**Comment by ulamnet** [comment]
which service provider ?  ı have a just leancloud keys .

**Comment by volio** [comment]
[Qiniu Storage](http://www.qiniu.com)
[Leancloud](https://leancloud.cn)
[Lecloud](http://www.lecloud.com)

**Comment by solarhell** [comment]
[LeTV](http://www.lecloud.com/) this is used to stream media.

**Comment by ulamnet** [comment]
Lecloud and Qiniu Storage ask Chinese phone number . I living in Turkey. Maybe you create key for me ? thanks.

**Comment by solarhell** [comment]
In fact with LeTV's api key you can just run the app.
And you can use cloud storage service which is available in your country.

**Comment by ulamnet** [comment]
parse aviable ?

**Comment by volio** [comment]
Lecloud can use Turkey phone number.

**Comment by solarhell** [comment]
Qiniu is used to storage some images.You can host them in your server instead.

**Comment by ulamnet** [comment]
which for open broadcast server ?

**Comment by solarhell** [comment]
As i just mentioned, `LeCloud is used to stream media.`

**Comment by volio** [comment]
Lecloud. Qiniu Storage is used for saving cover.

**Comment by ulamnet** [comment]
Lecloud doesnt accept Turkey phone number .
![lecloud](https://cloud.githubusercontent.com/assets/583003/17927137/f269415a-69fc-11e6-9533-2a4f2e6040e2.PNG)

**Comment by solarhell** [comment]
Come here, guy. http://www.lecloud.com/en-us/

**Comment by volio** [comment]
You should choose your country first.
![image](https://cloud.githubusercontent.com/assets/10475064/17927183/093c28c8-6a27-11e6-9a28-cae79758e9f8.png)

**Comment by solarhell** [comment]
BTW, you know Chinese?

**Comment by ulamnet** [comment]
I using translate.

**Comment by ulamnet** [comment]
http://usuc.lecloud.com/ this page not working .

**Comment by volio** [comment]
It doesn't matter. The web console url is [live.lecloud.com](http://live.lecloud.com/). And the url which can get user key is [uc.lecloud.com](http://uc.lecloud.com/userView/userKeyView.do)

**Comment by ulamnet** [comment]
I mean Turkey phone extension nothing showing this site.

**Comment by ulamnet** [comment]
Okay . now found

**Comment by ulamnet** [comment]
How to get keys in lecloud ?

**Comment by volio** [comment]
It's here
![image](https://cloud.githubusercontent.com/assets/10475064/17927976/f4dd38e6-6a2a-11e6-864d-3a90cb738451.png)

**Comment by ulamnet** [comment]
Thanks . In .htaccess problem ? http://vidumy.com/public/

page doesnt work.

**Comment by volio** [comment]
You should search this problem with Google or StackOverflow. Many answer in there about Laravel.

**Comment by ulamnet** [comment]
This problem get I write after  lecloud keys .

**Comment by volio** [comment]
I think you should try to learn how to deploy the Laravel Framework. It's helpful for you to deploy this application.

**Comment by ulamnet** [comment]
when ı write lecloud keys  in .env file  ı get this error

.http://vidumy.com/public/

**Comment by solarhell** [comment]
RTFM.
First you should know how to make deploy this project.
We have an `nginx.conf` in README.md.
You should set the web root to the `public` folder and let php-fpm serve the request.

**Comment by ulamnet** [comment]
I deploy this project. and configure nginx.conf but still doesnt show obs key.

http://vidumy.com/public/

**Comment by ulamnet** [comment]
![obs](https://cloud.githubusercontent.com/assets/583003/17946827/a0dbc550-6a52-11e6-8a3a-82fe30f17b97.PNG) where this obs key for users live streaming ?

**Comment by ulamnet** [comment]
are you there?

**Comment by solarhell** [comment]
Click '开始直播' , then you will get your stream key.

**Comment by ulamnet** [comment]
ı click but refreshing live page. 

you can try : http://vidumy.com/public

**Comment by ulamnet** [comment]
http://recordit.co/n92jRcklGE

**Comment by solarhell** [comment]
In fact you did't deploy it correctly. You exposed your `.env`.
You should deploy it to the root path, not let user visit it whit `public` in url.

**Comment by ulamnet** [comment]
I deploy root http://www.vidumy.com/ but still not working.

**Comment by ulamnet** [comment]
are you there?

**Comment by ulamnet** [comment]
Pls help me for installation.

**Comment by ulamnet** [comment]
http://www.vidumy.com/ ı try again , and try again but no get obs key.

**Comment by ulamnet** [comment]
hey...

**Comment by ulamnet** [comment]
http://recordit.co/OXiAniVnJB

**Comment by ulamnet** [comment]
How to create live video category ?

**Comment by ulamnet** [comment]
? why closed this issue

**Comment by volio** [comment]
Please read the document carefully and not ask such a meaningless question here
