### ISSUE TITLE
Unknown column 'liveId' in table 'liveinfo'

### ISSUE THREAD

**Issue by grzhan** [volio/AnotherLive#5]
访问用户直播间地址出错：

```QueryException in Connection.php line 713:
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'liveId' in 'field list' (SQL: select `title`, `activityId`, `liveId` from `liveinfo` where `uid` = 1 limit 1)```

迁移文件 `2016_03_15_144209_create_liveinfo_table.php` 中，似乎确实没有 `liveId` 字段：

```
        Schema::create('liveinfo', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('uid')->unique();
            $table->integer('ctime')->index();
            $table->integer('category_id')->index();
            $table->string('title');
            $table->string('description');
            $table->string('activityId');
            $table->timestamps();
        });
```

看了下对应 Liveinfo 的 Model 似乎也没有 Accessor&Mutator。

当然也可能只是我看漏搞错了……但还是来问一下

（最后顺带赞下这个项目

**Comment by volio** [comment]
感谢指出，liveId字段在调试的时候漏写了（囧rz），已修复
